### ISSUE TITLE
Travis CI py27 and py34 tests both use Python 3.5

### ISSUE THREAD

**Issue by takac** [kragniz/python-etcd3#15]
```json
{
  "language": "python",
  "python": 3.5,
  "env": "TOXENV=py27",
...
}
```
Tests are only running against python 3.5.

**Comment by kragniz** [comment]
Tox handles the python version run on each job.

2.7 job tox logs:

```
============================= test session starts ==============================
platform linux2 -- Python 2.7.9, pytest-3.0.3, py-1.4.31, pluggy-0.4.0
rootdir: /home/travis/build/kragniz/python-etcd3, inifile: 
plugins: cov-2.4.0, hypothesis-3.5.3
```

3.4 job tox logs:
```
============================= test session starts ===============================
platform linux -- Python 3.4.2, pytest-3.0.3, py-1.4.31, pluggy-0.4.0
rootdir: /home/travis/build/kragniz/python-etcd3, inifile: 
plugins: cov-2.4.0, hypothesis-3.5.3
```

It's a bit confusing, since both tox and travis want to control the test matrix. It ends up being easier to just let tox deal with it, though. Python 3.5 isn't installed on the images travis uses by default, so it's set as the python version to make sure that it's available.

**Comment by takac** [comment]
OK my bad, trying to learn Travis ☠️
