### ISSUE TITLE
Docs show every method's args as *args, **kwargs

### ISSUE THREAD

**Issue by kragniz** [kragniz/python-etcd3#76]
For some reason the docs are displaying method arguments as `(*args, **kwargs)`.

eg `get_prefix(*args, **kwargs)` instead of `get_prefix(self, key_prefix, sort_order=None, sort_target='key')`

Not sure why this is happening, but it makes them really confusing so should be fixed.

**Comment by ulaskeles** [comment]
Sphinx is seeing the signature for the wrapping function instead of the original function. I have an open PR https://github.com/kragniz/python-etcd3/pull/245 that renders docs like this:

<img width="645" src="https://user-images.githubusercontent.com/570160/30998616-946e9490-a495-11e7-9ecd-7a1562ab94ae.png">
